services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "UTC"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks: [evolutiva]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [evolutiva]

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      # SQLALCHEMY_DATABASE_URI intentionally not set here.
      # The app builds it from DB_* vars if not provided, and will map 'localhost' to 'host.docker.internal' when running inside Docker.
      REDIS_URL: redis://redis:6379/0
      USE_SQLITE: "false"
      DEV_AUTOCREATE_DATA: "1"
      SEED_ON_START: "1"
      AUTO_DDL_ON_START: "0"
      WORKERS: ${WORKERS:-3}
      THREADS: ${THREADS:-4}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-120}
      RUN_MIGRATIONS: "1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    networks:
      - evolutiva

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["bash","-lc","python -m rq worker -u ${REDIS_URL:-redis://redis:6379/0} evolutiva"]
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      # Keep worker aligned with API DB connection (same logic as API)
      REDIS_URL: redis://redis:6379/0
      USE_SQLITE: "false"
      RUN_MIGRATIONS: "0"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - evolutiva

  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Executa build e copia para volume e encerra
    environment:
      VITE_API_URL: /api
    volumes:
      - webroot:/webroot
    command: ["/bin/sh","-c","npm run build >/dev/null 2>&1 || true; cp -r /out/* /webroot/ 2>/dev/null || true"]
    networks: [evolutiva]

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - webroot:/usr/share/nginx/html:ro
    # Permite alterar a porta host exportando HTTP_PORT (ex: HTTP_PORT=8080 docker compose up -d)
    ports:
      - "${HTTP_PORT:-80}:80"
      # ative 443 se tiver certificados:
      # - "443:443"
      # - ./infra/nginx/certs:/etc/nginx/certs:ro
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost/" ]
      interval: 30s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    networks: [evolutiva]

volumes:
  pgdata:
  redisdata:
  webroot:

networks:
  evolutiva:
    driver: bridge
