name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff black
      - name: Lint (ruff/black)
        run: |
          ruff check .
          black --check .
      - name: Tests
        env:
          DATABASE_URL: sqlite:///test.db
          SECRET_KEY: test
          USE_SQLITE: "true"
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=.

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install
        run: npm ci
      - name: Lint
        run: npx eslint . --max-warnings=0
      - name: Build
        env:
          VITE_API_URL: /api
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-build]
    steps:
      - uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t evolutiva-api:ci ./backend

      - name: Build frontend image
        run: docker build -t evolutiva-frontend:ci ./frontend

      # Exemplo para publicar em GHCR (opcional)
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Tag & Push
      #   run: |
      #     docker tag evolutiva-api:ci ghcr.io/${{ github.repository_owner }}/evolutiva-api:${{ github.sha }}
      #     docker tag evolutiva-frontend:ci ghcr.io/${{ github.repository_owner }}/evolutiva-frontend:${{ github.sha }}
      #     docker push ghcr.io/${{ github.repository_owner }}/evolutiva-api:${{ github.sha }}
      #     docker push ghcr.io/${{ github.repository_owner }}/evolutiva-frontend:${{ github.sha }}
